general.import = [
  #"~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  #"/home/dang/.config/alacritty/catppuccin-mocha.toml"
]
[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "Key0",     mods = "Command", action = "ResetFontSize" },
  { key = "Equals",   mods = "Command", action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Command", action = "DecreaseFontSize" }
]
